### ISSUE TITLE
YAMG-0 Base setup

### ISSUE THREAD

**Issue by andrew-malitchuk** [andrew-malitchuk/yet-another-mapper-generator#2]
**TODO:** 

- [x] add `:core`;
- [x] add `:processor`;
- [x] add `.toml`;
- [x] add `build-logic` folder;
- [x] add some base content for READMEs;
- [x] add LICENSE;
- [x] configure GitHub repo;
- [x] crate some simple App for PoC.

**Comment by andrew-malitchuk** [comment]
Closed due to duplicity.
