### ISSUE TITLE
YAMG-2 Common part

### ISSUE THREAD

**Issue by andrew-malitchuk** [andrew-malitchuk/yet-another-mapper-generator#4]
**TODO:**

- [x] specify model classes;
- [x] specify interfaces/abstract classes for mappers;
- [x] create annotation classes;
- [x] update README & add example of usage;
- [x] specify strategy etc.
